### PR TITLE
Winbuild

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
winbuild is still failing with the following error, which explains some of the commits above: 

```
Evaluation error: object 'Pedestrian' not found.
```

Source: https://win-builder.r-project.org/wvF2c7dJtNYc/00check.log

Frustrating and weird.

**Comment by layik** [comment]
Apologies @Robinlovelace just cannot catch up with the repo transfer & other changes. Though `44ecc40` is passing.

**Comment by Robinlovelace** [comment]
That latest push is failing after

```r
devtools::check_win_release()
```

https://win-builder.r-project.org/PZ8XT22ATLv7/00check.log

**Comment by Robinlovelace** [comment]
Merging anyway because there are some improvements in here. May revert the tidyverse removing code though at some point.

**Comment by layik** [comment]
👍

**Comment by layik** [comment]
Did I just inadvertently remove these? My apologies Robin!

**Comment by layik** [comment]
#82 in with apologies, I think it was both of us actively working on it.

**Pull request merged**
