### PR TITLE
Remove spatstat.core dependency (#217)

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Hitting this error on local computer:

```
==> devtools::check()

─────────────────────────────────────────────────────────────────────────────────────────────────────────
ℹ Installed roxygen2 version (7.2.1) doesn't match required version (7.1.2)
✖ check() will not re-document this package
─────────────────────────────────────────────────────────────────────────────────────────────────────────
── Building ────────────────────────────────────────────────────────────────────────────────── stats19 ──
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
─────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/home/rlatemin/github/ropensci/stats19/DESCRIPTION’ ...
─  preparing ‘stats19’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (6.5s)
   --- re-building ‘blog.Rmd’ using rmarkdown
   --- finished re-building ‘blog.Rmd’
   
   --- re-building ‘stats19-training-setup.Rmd’ using rmarkdown
   Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "stats19-training-setup", and the latter is "An introduction to road safety analysis with R: setup notes". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
   --- finished re-building ‘stats19-training-setup.Rmd’
   
   --- re-building ‘stats19-training.Rmd’ using rmarkdown
   
   Attaching package: 'lubridate'
   
   The following objects are masked from 'package:base':
   
       date, intersect, setdiff, union
   
   Warning: The vignette title specified in \VignetteIndexEntry{} is different from the title in the YAML metadata. The former is "Introducing stats19", and the latter is "Introduction to R for road safety: an introduction to R and practical exercises". If that is intentional, you may set options(rmarkdown.html_vignette.check_title = FALSE) to suppress this check.
   --- finished re-building ‘stats19-training.Rmd’
   
   --- re-building ‘stats19-vehicles.Rmd’ using rmarkdown
   --- finished re-building ‘stats19-vehicles.Rmd’
   
   --- re-building ‘stats19.Rmd’ using rmarkdown
   trying URL 'https://data.dft.gov.uk/road-accidents-safety-data/dft-road-casualty-statistics-accident-2017.csv'
   Content type 'application/vnd.ms-excel' length 21356274 bytes (20.4 MB)
   ==================================================
   downloaded 20.4 MB
   
   
    *** caught segfault ***
   address 0x57597e2dad73, cause 'memory not mapped'
   
   Traceback:
    1: format_stats19(x, type = "Accident")
    2: format_accidents(crashes_2017_raw)
    3: eval(expr, envir, enclos)
    4: eval(expr, envir, enclos)
    5: eval_with_user_handlers(expr, envir, enclos, user_handlers)
    6: withVisible(eval_with_user_handlers(expr, envir, enclos, user_handlers))
    7: withCallingHandlers(withVisible(eval_with_user_handlers(expr,     envir, enclos, user_handlers)), warning = wHandler, error = eHandler,     message = mHandler)
    8: handle(ev <- withCallingHandlers(withVisible(eval_with_user_handlers(expr,     envir, enclos, user_handlers)), warning = wHandler, error = eHandler,     message = mHandler))
    9: timing_fn(handle(ev <- withCallingHandlers(withVisible(eval_with_user_handlers(expr,     envir, enclos, user_handlers)), warning = wHandler, error = eHandler,     message = mHandler)))
   10: evaluate_call(expr, parsed$src[[i]], envir = envir, enclos = enclos,     debug = debug, last = i == length(out), use_try = stop_on_error !=         2L, keep_warning = keep_warning, keep_message = keep_message,     output_handler = output_handler, include_timing = include_timing)
   11: evaluate::evaluate(...)
   12: evaluate(code, envir = env, new_device = FALSE, keep_warning = !isFALSE(options$warning),     keep_message = !isFALSE(options$message), stop_on_error = if (is.numeric(options$error)) options$error else {        if (options$error && options$include)             0L        else 2L    }, output_handler = knit_handlers(options$render, options))
   13: in_dir(input_dir(), expr)
   14: in_input_dir(evaluate(code, envir = env, new_device = FALSE,     keep_warning = !isFALSE(options$warning), keep_message = !isFALSE(options$message),     stop_on_error = if (is.numeric(options$error)) options$error else {        if (options$error && options$include)             0L        else 2L    }, output_handler = knit_handlers(options$render, options)))
   15: eng_r(options)
   16: block_exec(params)
   17: call_block(x)
   18: process_group.block(group)
   19: process_group(group)
   20: withCallingHandlers(if (tangle) process_tangle(group) else process_group(group),     error = function(e) {        setwd(wd)        cat(res, sep = "\n", file = output %n% "")        message("Quitting from lines ", paste(current_lines(i),             collapse = "-"), " (", knit_concord$get("infile"),             ") ")    })
   21: process_file(text, output)
   22: knitr::knit(knit_input, knit_output, envir = envir, quiet = quiet)
   23: rmarkdown::render(file, encoding = encoding, quiet = quiet, envir = globalenv(),     output_dir = getwd(), ...)
   24: vweave_rmarkdown(...)
   25: engine$weave(file, quiet = quiet, encoding = enc)
   26: doTryCatch(return(expr), name, parentenv, handler)
   27: tryCatchOne(expr, names, parentenv, handlers[[1L]])
   28: tryCatchList(expr, classes, parentenv, handlers)
   29: tryCatch({    engine$weave(file, quiet = quiet, encoding = enc)    setwd(startdir)    output <- find_vignette_product(name, by = "weave", engine = engine)    if (!have.makefile && vignette_is_tex(output)) {        texi2pdf(file = output, clean = FALSE, quiet = quiet)        output <- find_vignette_product(name, by = "texi2pdf",             engine = engine)    }    outputs <- c(outputs, output)}, error = function(e) {    thisOK <<- FALSE    fails <<- c(fails, file)    message(gettextf("Error: processing vignette '%s' failed with diagnostics:\n%s",         file, conditionMessage(e)))})
   30: tools::buildVignettes(dir = ".", tangle = TRUE)
   An irrecoverable exception occurred. R is aborting now ...
   Segmentation fault (core dumped)
Error in `(function (command = NULL, args = character(), error_on_status = TRUE, …`:
! System command 'R' failed
---
Exit status: 1
stdout & stderr: <printed>
---
Backtrace:
 1. devtools::check(, check_dir = dirname(getwd()))
 2. withr::with_envvar(pkgbuild::compiler_flags(FALSE), action = "prefix", …
 3. base::force(code)
 4. pkgbuild::build(pkg$path, tempdir(), args = build_args, quiet = quiet, …
 5. withr::with_temp_libpaths(rcmd_build_tools(options$cmd, c(options$path, …
 6. base::force(code)
 7. pkgbuild::rcmd_build_tools(options$cmd, c(options$path, options$args), …
 8. pkgbuild::with_build_tools({ …
 9. base::withCallingHandlers(callr::rcmd_safe(..., env = env, spinner = FALSE, …
10. callr::rcmd_safe(..., env = env, spinner = FALSE, show = FALSE, …
11. callr:::run_r(options)
12. base::with(options, with_envvar(env, do.call(processx::run, c(list(bin, …
13. base::with.default(options, with_envvar(env, do.call(processx::run, …
14. base::eval(substitute(expr), data, enclos = parent.frame())
15. base::eval(substitute(expr), data, enclos = parent.frame())
16. callr:::with_envvar(env, do.call(processx::run, c(list(bin, args = real_cmdargs, …
17. base::force(code)
18. base::do.call(processx::run, c(list(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout…
19. (function (command = NULL, args = character(), error_on_status = TRUE, …
20. base::throw(new_process_error(res, call = sys.call(), echo = echo, …
21. | base::signalCondition(cond)
22. (function (e) …
23. asNamespace("callr")$err$throw(e)
Execution halted

Exited with status 1.
```

**Comment by agila5** [comment]
Hi @Robinlovelace! Happy to check it on Sunday 🙂

**Comment by Robinlovelace** [comment]
Nudge @agila5

**Comment by agila5** [comment]
> [R version 4.2.2 (Innocent and Trusting) prerelease versions](http://cran.r-project.org/src/base-prerelease) will appear starting Friday 2022-10-21. Final release is scheduled for Monday 2022-10-31.

An unlucky day for GHA. I will try it again in a few days when the R4.2.2 is completed. Anyway, the PR LGTM.

**Comment by Robinlovelace** [comment]
Thanks for the review @agila5, and let's hope GH actions auto-fix themselves soon!

**Pull request merged**
