### PR TITLE
Update readme, close #132

### LINKED ISSUE #132: Hex sticker/logo

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
What do you think of our new logo @agila5 ?

**Comment by Robinlovelace** [comment]
image

**Comment by Robinlovelace** [comment]
image

**Comment by agila5** [comment]
IMO it looks amazing! I would use the image with the white background, i.e. [here](https://raw.githubusercontent.com/ropensci/stats19/master/man/figures/logo.png)

**Comment by Robinlovelace** [comment]
What do you think guys? Heads-up @layik, @agila5, @wengraf and @mem48 ?

**Comment by wengraf** [comment]
Some road safety professionals are very sensitive to the use of crash imagery. I suggest you change it to something like a VMS style dot matrix font saying “CRASH AHEAD” or similar.

**Comment by Robinlovelace** [comment]
> Some road safety professionals are very sensitive to the use of crash imagery. I suggest you change it to something like a VMS style dot matrix font saying “CRASH AHEAD” or similar.

That is a good point @wengraf was hoping to get feedback on that. Given that it's such a sensitive topic I'm open to a more sedate + neutral visual message in the logo.

**Comment by Robinlovelace** [comment]
Would something like this be better @wengraf ?

image

**Comment by wengraf** [comment]
Suggest you used the VMS font here (https://www.roads.org.uk/fonts). See what that might get you

**Comment by Robinlovelace** [comment]
image

**Comment by layik** [comment]
Now that @wengraf has lead the way, I can also say can we have the logo to portray the science or at least the aim of reducing it rather than actually cars crashing? 

That is better Robin IMHO.

**Comment by Robinlovelace** [comment]
Source: https://www.1001fonts.com/high-speed-font.html#waterfall

**Comment by Robinlovelace** [comment]
Something like this could look good: 
image

**Comment by WillSERP** [comment]
> some road safety professionals are very sensitive to the use of crash imagery.
They are, and I think this is legitimate when talking about some materials used in education and engagement. There is evidence that "shock and horror" engagement materials may to do more harm than good. However I don't think this logo falls into that category and I would disagree with somebody who thought that this image was 'too much' in terms of crash imagery. STATS19 is, by definition, about collisions whereas road safety is about not having those collisions.

That said, aesthetically I actually prefer the logo @Robinlovelace subsequently suggested
https://user-images.githubusercontent.com/1825120/72347910-106f0f00-36d1-11ea-944e-eac7f5e6ebe1.png
It looks a bit like the display on an VMS sign but the dots also bring to mind lots of data points.

My only other comment is that some sort of collision iconography may be useful if you need people outside of road safety to have an intuitive understanding of the logo.

**Comment by Robinlovelace** [comment]
Thanks @WillSERP I will sleep on it and give it a good think. Any other ideas/suggestions welcome...

**Pull request closed without merging**
