### PR TITLE
222 cran message

### PR DESCRIPTION
**Pull request by Robinlovelace**
- Replace read_accidents with read_collisions
- Use _collisions throughout

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Heads-up @agila5 and @layik the tests now pass. Will merge. Post merge review welcome!

**Comment by layik** [comment]
@Robinlovelace well done on the sprint. LGTM, only thing for me would have been to [deprecate](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Deprecated) the `read_accidents` but you guys use R more than I do.

**Comment by Robinlovelace** [comment]
Thanks Layik, atm it's ensuring that it actually works with the new files. Seem to but not 100% especially on the massive dataset going back to 1979.

**Comment by agila5** [comment]
Hi everyone! Sorry for the late reply but thank you very much for working on this 🚀

**Pull request merged**
