### PR TITLE
Update schema, fix #228

### LINKED ISSUE #228: format_sf fails
```
x = fatalities
n = names(x)
coords = n[grep(pattern = "easting|northing", x = n, ignore.case = TRUE)]
coords[1]
# [1] "location_easting_osgr"
# Identify rows with NA in coords columns:
x[[coords[1]]] | x[[coords[2]]]
```

```

Error in x[[coords[1]]] | x[[coords[2]]] : 
  operations are possible only for numeric, logical or complex types
```

### PR DESCRIPTION
**Pull request by Robinlovelace**

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Please review when you get a chance @agila5 and @layik

**Comment by layik** [comment]
Sorry @Robinlovelace a little more time next time please.

**Comment by Robinlovelace** [comment]
Yeah sorry for late notice, just needed it for #30MapDayChallenge!

**Comment by agila5** [comment]
Hi Robin! Unfortunately, I'm late to the party, but I think the fix you applied is correct. 

Sorry...
Andrea

**Comment by Robinlovelace** [comment]
All good, thanks for the replies guys!

**Pull request merged**
