### PR TITLE
Updates ready for next release

### PR DESCRIPTION
**Pull request by Robinlovelace**
Heads-up @layik, @agila5 and @wengraf I was planning on waiting until a new training manual for a major 2.0.0 update but it looks like I'll need to update the package on CRAN before then to prevent it from being archived. See #162.

This represents a 1.2.0 version on the way towards 2.0.0. Any comments on that welcome.

### CODE REVIEW

**Comment by agila5** [comment]
LGTM.  Maybe we should also test with the [new](https://twitter.com/krlmlr/status/1233884645508468738) version of `tibble` but I don't know how to update R on the Rstudio server and how to test the package for Debian 😭

**Comment by Robinlovelace** [comment]
Thanks @agila5, does this not work?:

```r
devtools::install_github("tidyverse/tibble")
```

Will try now in any case.

**Comment by Robinlovelace** [comment]
Testing now in any case...

**Comment by Robinlovelace** [comment]
Good news, all tests pass with dev version of `tibble()` (good news for @kmlr : )

```
==> devtools::check()

Updating stats19 documentation
Writing NAMESPACE
Loading stats19
Data provided under OGL v3.0. Cite the source and link to:
www.nationalarchives.gov.uk/doc/open-government-licence/version/3/
Writing NAMESPACE
── Building ────────────────────────────────────────────────────────────────────────────── stats19 ──
Setting env vars:
● CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
● CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
● CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
─────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/atfutures/repos/stats19/DESCRIPTION’ ...
─  preparing ‘stats19’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (38.2s)
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘stats19_1.2.0.tar.gz’
   
── Checking ────────────────────────────────────────────────────────────────────────────── stats19 ──
Setting env vars:
● _R_CHECK_CRAN_INCOMING_USE_ASPELL_: TRUE
● _R_CHECK_CRAN_INCOMING_REMOTE_    : FALSE
● _R_CHECK_CRAN_INCOMING_           : FALSE
● _R_CHECK_FORCE_SUGGESTS_          : FALSE
● NOT_CRAN                          : true
── R CMD check ─────────────────────────────────────────────────────────────────
* using log directory ‘/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/atfutures/repos/stats19.Rcheck’
* using R version 3.6.2 (2019-12-12)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘stats19/DESCRIPTION’ ... OK
* this is package ‘stats19’ version ‘1.2.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking serialization versions ... OK
* checking whether package ‘stats19’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking for future file timestamps ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  ‘figure’
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
** found \donttest examples: check also with --run-donttest
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘skip-download.R’
  Running ‘testthat.R’ [67s/68s]
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking re-building of vignette outputs ... OK
* checking for detritus in the temp directory ... OK
* DONE

Status: 1 NOTE
See
  ‘/mnt/57982e2a-2874-4246-a6fe-115c199bc6bd/atfutures/repos/stats19.Rcheck/00check.log’
for details.


── R CMD check results ────────────────────────────────────── stats19 1.2.0 ────
Duration: 2m 1s

❯ checking top-level files ... NOTE
  Non-standard file/directory found at top level:
    ‘figure’

0 errors ✔ | 0 warnings ✔ | 1 note ✖

R CMD check succeeded
```

**Comment by Robinlovelace** [comment]
Heads-up @krlmlr FYI, no breaks on our pkg.

**Comment by agila5** [comment]
Actually I was thinking about testing it using a very current r-devel as you reported in https://github.com/ropensci/stats19/issues/161, i.e 

> These can be reproduced by checking with --as-cran using a very current
r-devel (r77865 or later),

and with debian system but I don't think it's really important.

**Comment by Robinlovelace** [comment]
CRAN and `devtools::check_win_devel()` does that for us.

**Pull request merged**
