### PR TITLE
Downgrade to R3.4 to be more backward compatible.

### PR DESCRIPTION
**Pull request by layik**
Please consider before accepting.

### CODE REVIEW

**Comment by sckott** [comment]
What is the reason for the bumped R version dependency?

**Comment by layik** [comment]
Backward compatibility? At least one container image and at least two user feedback: oh I had to update my R to use the package.

**Comment by sckott** [comment]
okay. I think R cmd check does check whether you need to have a min R version and what that wouuld be if so - if it doesn't throw any warning about R version then it can be omitted I think - see discussion in https://community.rstudio.com/t/determining-which-version-of-r-to-depend-on/4396/10

**Comment by Robinlovelace** [comment]
I think it needs 3.5.0 for latest sf.

**Comment by layik** [comment]
Thanks @sckott, that is a good post by Hadley.

> I think that means in most cases, if there is any doubt, you should simply omit the version specification. In the tidyverse we are taking a more aggressive approach (because we have more R package development time/resources available to us), slowly pushing the tested version of R back to 3.1

@Robinlovelace backward compatibility could still be argued even if non-target version is negligible. But again, `tidyverse` seems to be doing what I think is right for all software development.

**Comment by layik** [comment]
As for dependency version check, apparently (again from Hadley's post) there is no way to check. I just checked our DESCRIPTION:

1. We only rely on `sf` and `readr`
2. `sf` depends on 3.3.0 https://github.com/r-spatial/sf/blob/master/DESCRIPTION#L51
3. `readr` depends on 3.1 https://github.com/tidyverse/readr/blob/master/DESCRIPTION#L18

**Comment by Robinlovelace** [comment]
There is a way to test it. @layik please can you try to reproduce the following:

```
# Aim: test stats19 on old rocker version

docker run --rm -it rocker/geospatial:3.4.0 /bin/bash
R
devtools::install_github("ropensci/stats19")
devtools::install_github("ropensci/stats19", ref = "r3.4")
```

**Comment by layik** [comment]
I think the merge is sensible, thanks @Robinlovelace. I will do the deps check at a later time :)

**Comment by Robinlovelace** [comment]
Already did the checks, hence merge. But it's worth trying to reproduce the result: reproducible testing of backward compatibility.

**Pull request merged**
