### PR TITLE
add travis matrix

### PR DESCRIPTION
**Pull request by mpadge**
Coz this should be done at some stage. Let's see how the tests go on all these different systems ...

Note the deploy changes, which I just learned about - this deploys only on the specified architecture.

### CODE REVIEW

**Comment by layik** [comment]
Thanks @mpadge. `.travis.yml` skill is hard to acquire.

**Comment by mpadge** [comment]
Ah, travis is not set up to check remote PRs, so there are no results from there. Maybe just merge and then see ...? It may well fail, but (1) as said, this will be needed at some stage anyway; and (2) we'll learn from any failures.

**Comment by layik** [comment]
I will do a bit more digging on this Mark before I give any opinion here.

**Comment by layik** [comment]
Definitely no harm in a push and reset IF fails!

**Comment by Robinlovelace** [comment]
@mpadge you happy to look at the results of this if I merge later today? Thanks for creating this and sorry it's taken so long to look at it - was prioritising other things. But think it will be awesome if it works!

**Comment by mpadge** [comment]
yeah, I'll follow up post-merge if things go wrong ...

**Pull request merged**
